name: "iobroker"
version: "v10.0.0"
slug: "iobroker"
description: "Add-On für den ioBroker basierend auf buanet/iobroker:v10.0.0"
arch:
  - amd64
  - armv7
  - arm64
ports:
  8081/tcp: 8081
  18883/tcp: 18883
map:
  config: false
  ssl: false
  addons: true  # Aktiviert den Zugriff auf `/addon_configs`
options:
  iobroker_folder: "/addon_configs/iobroker"
schema:
  iobroker_folder:
    description: "Pfad des lokalen Ordners für ioBroker-Daten (standardmäßig /addon_configs/iobroker)"
    type: string
    default: "/addon_configs/iobroker"
startup: "services"
host_network: false
privileged: true
timeout: 60
