name: custom-at-ioBroker
version: 1.0.0
slug: custom-at-ioBroker
description: Home Assistant Add-on for ioBroker
url: https://github.com/alientim/homeassistant-addon-repository/iobroker
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
image: buanet/iobroker-{arch}
map:
  - addon_configs:rw
init: false
panel_icon: mdi:home-automation
options:
  config_path: "/addon_configs/iobroker"
  log_level: info
schema:
  config_path: str
  log_level: list(info|debug)?
